version: '2'
services:
  jenkins:
    container_name: 'jenkins'
    image: 'jenkins/jenkins'
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - '8880:8080'
      - '50000:50000'
    group_add:
      - '998'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /var/jenkins/data:/var/jenkins_home
      - /usr/local/apache-maven-3.8.6:/usr/local/apache-maven-3.8.6